const recipePlaceholderImagePath = "assets/images/empty_plate.png";
const imageNotFoundPath = "assets/images/image_not_found.png";
const recipeImages = {
  "assets/images/salad.png",
  "assets/images/chicken_and_rice.png",
  "assets/images/fried_rice.png",
  "assets/images/ramen.png",
  "assets/images/rice.png",
  "assets/images/salmon.png",
  "assets/images/spaghetti.png",
  "assets/images/meatballs.png",
  "assets/images/lasagna.png",
  "assets/images/pizza_v2.png",
  "assets/images/pizza.png",
  "assets/images/tortilla.png",
  "assets/images/taco.png",
  "assets/images/snack.png",
  "assets/images/hamburger.png",
  "assets/images/soup.png",
  "assets/images/porridge.png",
  "assets/images/bun.png",
  "assets/images/bread.png",
  "assets/images/drink.png",
  "assets/images/jar.png",
  "assets/images/pie.png",
  "assets/images/cake.png",
  "assets/images/cake_v2.png",
  "assets/images/cake_piece.png",
  "assets/images/cake_v3.png",
  "assets/images/pancakes.png",
  "assets/images/waffles.png",
  "assets/images/cookie.png",
  "assets/images/cupcake.png",
  "assets/images/muffin.png",
  "assets/images/muffin_v2.png",
  "assets/images/roll.png",
};
