// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdazOEbdsCCftifvhuZP1IIpaeZ1SVWzc',
    appId: '1:953147600105:web:5918ac0317451fc2521478',
    messagingSenderId: '953147600105',
    projectId: 'my-groovy-recipes',
    authDomain: 'my-groovy-recipes.firebaseapp.com',
    storageBucket: 'my-groovy-recipes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrnGoA0F1aFoxN9abBB1Iu3aLIpoK86cQ',
    appId: '1:953147600105:android:ed59141b9eac244d521478',
    messagingSenderId: '953147600105',
    projectId: 'my-groovy-recipes',
    storageBucket: 'my-groovy-recipes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClH9lddy6XxZfxsUFvps8EnoYhV1_0UF8',
    appId: '1:953147600105:ios:f361d84c12a1d9c1521478',
    messagingSenderId: '953147600105',
    projectId: 'my-groovy-recipes',
    storageBucket: 'my-groovy-recipes.appspot.com',
    androidClientId: '953147600105-g7a67j2d60pnrf0u3o5t8i5es03l5el1.apps.googleusercontent.com',
    iosClientId: '953147600105-a63dnhlrkueu7pb07efbil2v539npcjb.apps.googleusercontent.com',
    iosBundleId: 'com.example.myGroovyRecipes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClH9lddy6XxZfxsUFvps8EnoYhV1_0UF8',
    appId: '1:953147600105:ios:e7ff4ab020e8da5c521478',
    messagingSenderId: '953147600105',
    projectId: 'my-groovy-recipes',
    storageBucket: 'my-groovy-recipes.appspot.com',
    androidClientId: '953147600105-g7a67j2d60pnrf0u3o5t8i5es03l5el1.apps.googleusercontent.com',
    iosClientId: '953147600105-1f06cfu6lm79lg71fru812fsra1cn7g7.apps.googleusercontent.com',
    iosBundleId: 'com.example.myGroovyRecipes.RunnerTests',
  );
}
