// schema for recipes
const ownerUserIdFieldName = "user_id";
const stepsFieldName = "steps";
const nameFieldName = "name";
const portionsFieldName = "portions";
const ingredientsFieldName = "ingredients";
const imageFieldName = "image";
const tagsFieldName = "tags";
const descriptionFieldName = "description";
